// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppEquation: typeof import('./components/AppEquation.vue')['default']
    Btn: typeof import('./components/Btn.vue')['default']
    ButtonToTheTop: typeof import('./components/ButtonToTheTop.vue')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    MiniNavigationBar: typeof import('./components/MiniNavigationBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TheAtom: typeof import('./components/TheAtom.vue')['default']
  }
}

export {}
